[[cells]]
name = "xins"
enable_type_id = true
location = { file = "build/xins_rce" }

# Replace with your own lock if you want to unlock deployed cells.
# For example the secp256k1 lock
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x9b79d38b5503381162b645ad714dbd1f1de242d2"
hash_type = "type"

